language: python

os:
  - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

env:
  - CXX=g++-7 LUA="lua=5.1"
  - CXX=g++-7 LUA="lua=5.2"
  - CXX=g++-7 LUA="lua=5.3"
  - CXX=g++-7 LUA="lua=5.4"
  - CXX=g++-7 LUA="luajit=2.0"
  - CXX=g++-7 LUA="luajit=2.1"

jobs:
  include:
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
      env: LUA="lua=5.1"
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
      env: LUA="lua=5.4"

before_install:
  - pip install hererocks
  - hererocks lua_install -r^ --$LUA
  - export PATH=$PATH:$PWD/lua_install/bin # Add directory with all installed binaries to PATH
  - luarocks install lua-cjson2

install:
  - luarocks make
  - luarocks install busted

script:
  - busted --verbose
